version: "3.7"

services:
  apache:
    image: httpd
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/

    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
